#!/usr/bin/env bash


# 通知函数
function notify {
    local title=$1
    local content=$2 
    local script='display notification "'$2'" with title "'$1'"'
    osascript -e "$script"
}


# 检查配置
if [[ $1 != "sz" && $1 != "rz" ]]; then
    notify "警告" "配置-调用脚本必须为 rz|sz"
    exit
fi

# 取消
function cancel {
	echo -e \\x18\\x18\\x18\\x18\\x18
}


#setup
[[ $LRZSZ_PATH != "" ]] && LRZSZ_PATH=":$LRZSZ_PATH" || LRZSZ_PATH=""

PATH=$(command -p getconf PATH):/usr/local/bin$LRZSZ_PATH
ZCMD=$(
    if command -v $1 >/dev/null 2>&1; then
        echo "$1"
    elif command -v l$1 >/dev/null 2>&1; then
        echo "l$1"
    fi
)

# main
if [[ $ZCMD = "" ]]; then
    cancel
    
    notify "警告" "找不到 Z-Modem tools，是否安装lrzsz"
    exit
elif [[ $1 = "rz" ]]; then
    # receive a file
    DST=`osascript \
        -e "tell application \"iTerm\" to activate" \
        -e "tell application \"iTerm\" to set thefile to choose folder with prompt \"Save To\"" \
        -e "do shell script (\"echo \"&(quoted form of POSIX path of thefile as Unicode text)&\"\")"
        `
    
    if [[ $DST = "" ]]; then
        cancel
        notify "提示" "取消发送!"
        exit
    fi

	cd "$DST"
	
    notify "提示" "开始发送\n$DST"

    $ZCMD -E -e -b -y 2>&1

    notify "提示" "完成发送\n$DST"
else
    # 下载文件
    SRC=`osascript \
            -e "tell application \"iTerm\" to activate" \
            -e "tell application \"iTerm\" to set thefile to choose file with prompt \"Choose a file to download\"" \
            -e "do shell script (\"echo \"&(quoted form of POSIX path of thefile as Unicode text)&\"\")"
    `

    if [[ $SRC = "" ]]; then
        cancel
        notify "提示" "取消下载"
        exit
    fi

    notify "提示" "开始下载\n$SRC"

    $ZCMD -E -e -b "$SRC" 2>&1


    notify "提示" "完成下载\n$SRC"
fi
